<?php
global $test;
global $student_records;
  $student_records = [
    0=> [
      'name' => 'Purnima Adhikari',
      'address' => 'shantinagar',
      'email' => 'nima@gmail.com',
      'contact' => 9860563921,
      ],
      1 => [
      'name' => 'Nirja Bahety',
      'address' => 'anamnagar',
      'email' => 'nirju@gmail.com',
      'contact' => 9850543921,
      ],
      2 => [
      'name' => 'Kamana Sharma',
      'address' => 'kalanki',
      'email' => 'kamana01@gmail.com',
       'contact' => 9810568901,
      ],
      3 => [
      'name' => 'Bandana shrestha',
      'address' => 'balkumari',
      'email' => 'bandu@gmail.com',
       'contact' => 9760963921,
      ],
    ];
